// File generated by Gambit v4.9.3
// Link info: (409003 (js ((compactness 9))) "foo" (("foo")) (module_register ctrlpt_init parententrypt_init make_interned_symbol glo check_procedure_glo poll string base92_decode r1 wrong_nargs nargs) (display) () () #f)

_cst0__foo = new _ScmString(_z("cWcKcLcVCcLcVCc)cRcRDD"));

_cst1__foo = _i("display");

_m(_bb1_foo_23_ = () => {
if (_n !== 0) {
return _w(_bb1_foo_23_);
}
_a = _cst0__foo;
return _p(_bb2_foo_23_);
},-1,_i("foo#"),!1,!0);

_j(_bb2_foo_23_ = () => {
_n = 1;
return _u(_g[_cst1__foo.r],_cst1__foo)();
});



_module_register([[_i("foo")],[],null,1,_bb1_foo_23_,!1]);

